import { Outfit } from "next/font/google";  // Changed to capital O
import "./globals.css";
import { Toaster } from 'react-hot-toast';



const outfit = Outfit({  // Use Outfit (imported) to create outfit instance
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Growth Grid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}